name: Auto-Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build-all:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Static Data
        run: |
          ./bin/ctl db refresh-static

      - name: Install fyne-cross
        run: |
          set -euo pipefail
          git clone https://github.com/kava-forge/fyne-cross.git
          cd fyne-cross
          go install .
          export PATH="$(go env GOPATH)/bin:$PATH"
          which fyne-cross

      - name: Build
        run: |
          set -euo pipefail
          export PATH="$(go env GOPATH)/bin:$PATH"
          ./bin/ctl build release windows \*
          mv fyne-cross/dist/windows-amd64/EVEAlts.exe.zip fyne-cross/dist/windows-amd64/EVEAlts-windows-amd64.exe.zip
          mv fyne-cross/dist/windows-arm64/EVEAlts.exe.zip fyne-cross/dist/windows-arm64/EVEAlts-windows-arm64.exe.zip
          mv fyne-cross/dist/windows-386/EVEAlts.exe.zip fyne-cross/dist/windows-386/EVEAlts-windows-386.exe.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          fail_on_unmatched_files: true
          files: |
            fyne-cross/dist/windows-amd64/EVEAlts-windows-amd64.exe.zip
            fyne-cross/dist/windows-arm64/EVEAlts-windows-arm64.exe.zip
            fyne-cross/dist/windows-386/EVEAlts-windows-386.exe.zip